CREATE TABLE Users (
UserID INT NOT NULL AUTO_INCREMENT,
Username VARCHAR(255) NOT NULL UNIQUE,
Email VARCHAR(255) NOT NULL,
Password VARCHAR(255) NOT NULL,
IsAdmin BOOLEAN NOT NULL DEFAULT 0,
ProfilePicture VARCHAR(255) NOT NULL DEFAULT 'default.jpg',
AboutMe VARCHAR(255),
PRIMARY KEY(UserID)
)engine=InnoDB;
CREATE TABLE Movies (
Name VARCHAR(255) NOT NULL,
Poster VARCHAR(255) NOT NULL DEFAULT 'default.jpg',
MovieID INT NOT NULL AUTO_INCREMENT,
ReleaseDate INT NOT NULL,
Description VARCHAR(255) NOT NULL,
AddDate DATETIME NOT NULL,
PRIMARY KEY(MovieID)
)engine=InnoDB;
CREATE TABLE Friends (
UserID INT NOT NULL,
UserID2 INT NOT NULL,
Status BOOLEAN NOT NULL,
FOREIGN KEY(UserID) REFERENCES Users(UserID),
FOREIGN KEY(UserID2) REFERENCES Users(UserID),
PRIMARY KEY(UserID, UserID2)
)engine=InnoDB;
CREATE TABLE Comments (
CommentID INT NOT NULL AUTO_INCREMENT,
UserID INT NOT NULL,
MovieID INT NOT NULL,
Comment VARCHAR(255) NOT NULL,
AddTime DATETIME NOT NULL,
PRIMARY KEY(CommentID),
FOREIGN KEY(UserID) REFERENCES Users(UserID),
FOREIGN KEY(MovieID) REFERENCES Movies(MovieID)
)engine=InnoDB;
CREATE TABLE Ratings (
UserID INT NOT NULL,
MovieID INT NOT NULL,
Rating INT NOT NULL,
AddTime DATETIME NOT NULL,
FOREIGN KEY(UserID) REFERENCES Users(UserID),
FOREIGN KEY(MovieID) REFERENCES Movies(MovieID),
PRIMARY KEY(UserID, MovieID)
)engine=InnoDB;
CREATE TABLE Crew (
CrewID INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(255) NOT NULL,
Role VARCHAR(255) NOT NULL,
PRIMARY KEY(CrewID)
)engine=InnoDB;
CREATE TABLE Credits (
MovieID INT NOT NULL,
CrewID INT NOT NULL,
FOREIGN KEY(MovieID) REFERENCES Movies(MovieID),
FOREIGN KEY(CrewID) REFERENCES Crew(CrewID),
PRIMARY KEY(MovieID, CrewID)
)engine=InnoDB;